#!/usr/bin/env node
import { create, fromBinary, toBinary } from '@bufbuild/protobuf'
import { CodeGeneratorRequestSchema, CodeGeneratorResponseSchema } from '@bufbuild/protobuf/wkt'
import { resolveMethods } from './gen/resolve.js'

const chunks = []
for await (const c of process.stdin) chunks.push(c)
const req = fromBinary(CodeGeneratorRequestSchema, new Uint8Array(Buffer.concat(chunks)))

const responseFiles = []
for (const f of req.protoFile) {
  if (!req.fileToGenerate.includes(f.name)) continue
  const methods = resolveMethods(f, req)
  if (methods.length === 0) continue
  const base = f.name.replace(/\.proto$/, '')
  responseFiles.push({ name: `${base}_easyrpc.ts`, content: render(methods) })
}
const resp = create(CodeGeneratorResponseSchema, { file: responseFiles })
process.stdout.write(Buffer.from(toBinary(CodeGeneratorResponseSchema, resp)))

function render(methods) {
  const lines = []
  lines.push(`// Code generated by protoc-gen-easyrpc-ts. DO NOT EDIT.`)
  lines.push(`import type { MethodSpec } from '@easy-utils/easy-rpc/protocol'`)
  lines.push(``)
  lines.push(`export const methodSpecs: MethodSpec[] = [`)
  for (const m of methods) {
    lines.push(`  { service: ${JSON.stringify(m.service)}, name: ${JSON.stringify(m.name)}, path: ${JSON.stringify(m.path)}, httpMethod: ${JSON.stringify(m.httpMethod)}, clientStream: ${m.clientStream}, serverStream: ${m.serverStream}, body: ${JSON.stringify(m.body)} },`)
  }
  lines.push(`]`)
  lines.push(``)
  return lines.join('\n') + '\n'
}
