#!/usr/bin/env node
import { create, fromBinary, toBinary, toJson, fromJson } from '@bufbuild/protobuf'
import { CodeGeneratorRequestSchema, CodeGeneratorResponseSchema } from '@bufbuild/protobuf/wkt'
import { resolveMethods } from './gen/resolve.js'

const chunks = []
for await (const c of process.stdin) chunks.push(c)
const req = fromBinary(CodeGeneratorRequestSchema, new Uint8Array(Buffer.concat(chunks)))

const responseFiles = []
for (const f of req.protoFile) {
  if (!req.fileToGenerate.includes(f.name)) continue
  const methods = resolveMethods(f, req)
  if (methods.length === 0) continue
  const services = collectServices(f, methods)
  const base = f.name.replace(/\.proto$/, '')
  responseFiles.push({ name: `${base}_easyrpc.ts`, content: render(f, methods, services) })
}
const resp = create(CodeGeneratorResponseSchema, { file: responseFiles })
process.stdout.write(Buffer.from(toBinary(CodeGeneratorResponseSchema, resp)))

function lastType(t){ if(!t) return ''; const i=String(t).lastIndexOf('.'); return i>=0?String(t).slice(i+1):String(t) }
function collectServices(file, methods){
  const svcs=[]
  for (const svc of file.service ?? []) {
    const svcName=svc.name??''
    const list=[]
    for (const m of svc.method ?? []) {
      const meta=methods.find(x=>x.name===(m.name??'')&&x.service.endsWith(svcName))
      list.push({name:m.name??'', inMsg:lastType(m.inputType), outMsg:lastType(m.outputType),
        serverStream:m.serverStreaming===true, path:meta?.path??`/${m.name}`, httpMethod:meta?.httpMethod??'POST'})
    }
    svcs.push({name:svcName, methods:list})
  }
  return svcs
}

function render(file, unmapped, services){
  const lines=[]
  lines.push(`// Code generated by protoc-gen-easyrpc-ts. DO NOT EDIT.`)
  lines.push(`import { fromBinary, toBinary, toJson, fromJson } from '@bufbuild/protobuf'`)
  lines.push(`import { toBytes, fromBytesToJson } from 'easy-rpc/protocol'
import type { Transport, MethodSpec } from 'easy-rpc/protocol'`)
  lines.push(`import type { ServiceHandlers, ContentKind } from 'easy-rpc/server'`)
  const msgNames=collectMsgNames(file)
  if(msgNames.length) lines.push(`import { ${msgNames.join(', ')}, ${msgNames.map(n=>n+'Schema').join(', ')} } from './${baseName(file)}_pb.js'`)
  lines.push(``)
  lines.push(`export const methodSpecs: MethodSpec[] = [`)
  for(const m of unmapped) lines.push(`  { service: ${JSON.stringify(m.service)}, name: ${JSON.stringify(m.name)}, path: ${JSON.stringify(m.path)}, httpMethod: ${JSON.stringify(m.httpMethod)}, clientStream: ${m.clientStream}, serverStream: ${m.serverStream}, body: ${JSON.stringify(m.body)} },`)
  lines.push(`]`)
  lines.push(``)

  for(const svc of services){
    const iface=`${svc.name}Client`, clientName=`create${svc.name}Client`
    lines.push(`export interface ${iface} {`)
    for(const m of svc.methods){ const ret=m.serverStream?`Promise<AsyncIterable<${m.outMsg}>>`:`Promise<${m.outMsg}>`; lines.push(`  ${camel(m.name)}(req: ${m.inMsg}, kind?: ContentKind): ${ret}`) }
    lines.push(`}`)
    lines.push(``)
    lines.push(`export function ${clientName}(transport: Transport, defaultKind: ContentKind = 'proto'): ${iface} {`)
    lines.push(`  return {`)
    for(const m of svc.methods){
      lines.push(`    async ${camel(m.name)}(req, kind = defaultKind) {`)
      lines.push(`      const url = ${JSON.stringify(m.path)}`)
      lines.push(`      const isJson = kind === 'json'`)
      if(m.serverStream){
        lines.push(`      const ct = isJson ? 'application/connect+json' : 'application/connect+proto'`)
        lines.push(`      const stream = await transport.openStream({ url, method: 'POST', headers: { 'content-type': [ct], accept: [ct] }, body: isJson ? toBytes(toJson(${m.inMsg}Schema, req)) : toBinary(${m.inMsg}Schema, req) })`)
        lines.push(`      return (async function* (): AsyncIterable<${m.outMsg}> { for await (const chunk of stream) { yield isJson ? fromJson(${m.outMsg}Schema, fromBytesToJson(chunk)) : fromBinary(${m.outMsg}Schema, chunk) } })()`)
      } else {
        lines.push(`      const ct = isJson ? 'application/json' : 'application/proto'`)
        lines.push(`      const res = await transport.send({ url, method: ${JSON.stringify(m.httpMethod)}, headers: { 'content-type': [ct], accept: [ct] }, body: isJson ? toBytes(toJson(${m.inMsg}Schema, req)) : toBinary(${m.inMsg}Schema, req) })`)
        lines.push(`      if (res.error) throw res.error`)
        lines.push(`      return isJson ? fromJson(${m.outMsg}Schema, fromBytesToJson(res.body)) : fromBinary(${m.outMsg}Schema, res.body)`)
      }
      lines.push(`    },`)
    }
    lines.push(`  }`)
    lines.push(`}`)
    lines.push(``)
    lines.push(`export interface ${svc.name}ServiceImpl {`)
    for(const m of svc.methods){ const ret=m.serverStream?`AsyncIterable<${m.outMsg}>`:`Promise<${m.outMsg}>`; lines.push(`  ${camel(m.name)}(req: ${m.inMsg}): ${ret}`) }
    lines.push(`}`)
    lines.push(``)
    lines.push(`export function ${svc.name}Handlers(impl: ${svc.name}ServiceImpl): ServiceHandlers {`)
    lines.push(`  const unary: ServiceHandlers['unary'] = {}`)
    lines.push(`  const stream: ServiceHandlers['stream'] = {}`)
    for(const m of svc.methods){
      const dec = `kind==='json'?fromJson(${m.inMsg}Schema, fromBytesToJson(input)):fromBinary(${m.inMsg}Schema, input)`
      if(m.serverStream){
        lines.push(`  stream[${JSON.stringify(m.name)}] = async (input, kind, emit) => {`)
        lines.push(`    const req = ${dec}`)
        lines.push(`    for await (const v of impl.${camel(m.name)}(req)) { await emit(kind==='json'?toBytes(toJson(${m.outMsg}Schema, v)):toBinary(${m.outMsg}Schema, v), false) }`)
        lines.push(`    await emit(new Uint8Array(0), true)`)
        lines.push(`  }`)
      } else {
        lines.push(`  unary[${JSON.stringify(m.name)}] = async (input, kind) => {`)
        lines.push(`    const req = ${dec}`)
        lines.push(`    const v = await impl.${camel(m.name)}(req)`)
        lines.push(`    return kind==='json'?toBytes(toJson(${m.outMsg}Schema, v)):toBinary(${m.outMsg}Schema, v)`)
        lines.push(`  }`)
      }
    }
    lines.push(`  return { unary, stream }`)
    lines.push(`}`)
    lines.push(``)
  }
  return lines.join('\n')+'\n'
}

function collectMsgNames(file){ const s=new Set(); for(const svc of file.service??[])for(const m of svc.method??[]){s.add(lastType(m.inputType));s.add(lastType(m.outputType))} return [...s] }
function baseName(file){ return (file.name||'').replace(/\.proto$/,'').split('/').pop() }
function camel(s){ return s ? s[0].toLowerCase()+s.slice(1) : '' }
