#!/usr/bin/env node
import { create, fromBinary, toBinary } from '@bufbuild/protobuf'
import { CodeGeneratorRequestSchema, CodeGeneratorResponseSchema } from '@bufbuild/protobuf/wkt'
import { resolveMethods } from './gen/resolve.js'

const chunks = []
for await (const c of process.stdin) chunks.push(c)
const req = fromBinary(CodeGeneratorRequestSchema, new Uint8Array(Buffer.concat(chunks)))

const responseFiles = []
for (const f of req.protoFile) {
  if (!req.fileToGenerate.includes(f.name)) continue
  const methods = resolveMethods(f, req)          // full method metadata incl. serverStream + path
  if (methods.length === 0) continue
  const services = collectServices(f, methods)
  const base = f.name.replace(/\.proto$/, '')
  responseFiles.push({ name: `${base}_easyrpc.ts`, content: render(f, methods, services) })
}
const resp = create(CodeGeneratorResponseSchema, { file: responseFiles })
process.stdout.write(Buffer.from(toBinary(CodeGeneratorResponseSchema, resp)))

function lastType(t) {
  if (!t) return ''
  const s = String(t)
  const i = s.lastIndexOf('.')
  return i >= 0 ? s.slice(i + 1) : s
}

// Build per-service method list bound to resolved metadata (path, streams).
function collectServices(file, methods) {
  const svcs = []
  for (const svc of file.service ?? []) {
    const svcName = svc.name ?? ''
    const list = []
    for (const m of svc.method ?? []) {
      const meta = methods.find(x => x.name === (m.name ?? '') && x.service.endsWith(svcName))
      list.push({
        name: m.name ?? '',
        inMsg: lastType(m.inputType),
        outMsg: lastType(m.outputType),
        clientStream: m.clientStreaming === true,
        serverStream: m.serverStreaming === true,
        path: meta?.path ?? `/${m.name}`,
        httpMethod: meta?.httpMethod ?? 'POST',
      })
    }
    svcs.push({ name: svcName, methods: list })
  }
  return svcs
}

function render(file, unmapped, services) {
  const lines = []
  lines.push(`// Code generated by protoc-gen-easyrpc-ts. DO NOT EDIT.`)
  lines.push(`import { fromBinary, toBinary } from '@bufbuild/protobuf'`)
  lines.push(`import type { Transport, MethodSpec } from 'easy-rpc/protocol'`)
  const msgNames = collectMsgNames(file)
  if (msgNames.length) {
    lines.push(`import { ${msgNames.join(', ')}, ${msgNames.map(n => n + 'Schema').join(', ')} } from './${baseName(file)}_pb.js'`)
  }
  lines.push(``)
  lines.push(`export const methodSpecs: MethodSpec[] = [`)
  for (const m of unmapped) {
    lines.push(`  { service: ${JSON.stringify(m.service)}, name: ${JSON.stringify(m.name)}, path: ${JSON.stringify(m.path)}, httpMethod: ${JSON.stringify(m.httpMethod)}, clientStream: ${m.clientStream}, serverStream: ${m.serverStream}, body: ${JSON.stringify(m.body)} },`)
  }
  lines.push(`]`)
  lines.push(``)

  for (const svc of services) {
    const clientName = `create${svc.name}Client`
    const interfaceName = `${svc.name}Client`
    lines.push(`export interface ${interfaceName} {`)
    for (const m of svc.methods) {
      const ret = m.serverStream ? `Promise<AsyncIterable<${m.outMsg}>>` : `Promise<${m.outMsg}>`
      lines.push(`  ${camel(m.name)}(req: ${m.inMsg}): ${ret}`)
    }
    lines.push(`}`)
    lines.push(``)
    lines.push(`export function ${clientName}(transport: Transport): ${interfaceName} {`)
    lines.push(`  return {`)
    for (const m of svc.methods) {
      lines.push(`    async ${camel(m.name)}(req) {`)
      lines.push(`      const url = ${JSON.stringify(m.path)}`)
      if (m.serverStream) {
        lines.push(`      const stream = await transport.openStream({ url, method: 'POST', headers: { 'content-type': ['application/connect+proto'] }, body: toBinary(${m.inMsg}Schema, req) })`)
        lines.push(`      return (async function* (): AsyncIterable<${m.outMsg}> {`)
        lines.push(`        for await (const chunk of stream) {`)
        lines.push(`          yield fromBinary(${m.outMsg}Schema, chunk)`)
        lines.push(`        }`)
        lines.push(`      })()`)
      } else {
        lines.push(`      const res = await transport.send({ url, method: ${JSON.stringify(m.httpMethod)}, headers: { 'content-type': ['application/proto'] }, body: toBinary(${m.inMsg}Schema, req) })`)
        lines.push(`      if (res.error) throw res.error`)
        lines.push(`      return fromBinary(${m.outMsg}Schema, res.body)`)
      }
      lines.push(`    },`)
    }
    lines.push(`  }`)
    lines.push(`}`)
    lines.push(``)
  }
  return lines.join('\n') + '\n'
}

function collectMsgNames(file) {
  const set = new Set()
  for (const svc of file.service ?? []) {
    for (const m of svc.method ?? []) {
      set.add(lastType(m.inputType))
      set.add(lastType(m.outputType))
    }
  }
  return [...set]
}
function baseName(file) { return (file.name || '').replace(/\.proto$/, '').split('/').pop() }
function camel(s) { return s ? s[0].toLowerCase() + s.slice(1) : '' }
